### PR TITLE
Integration of firebase and retrofit

### PR DESCRIPTION
**Pull request by fin1989**
Integrated retorfit2 and firebase auth

### CODE REVIEW

**Comment by Vovchyk** [comment]
@fin1989, could you please split this on two branches and two PRs? It'll be a bit more work, but will simplify our life in maintaining our repo logs.

Could you also use for that a convention where branch name is "rfr-<Issue Number>"? @Andruhin did it in that way.

**Comment by Vovchyk** [comment]
I would also suggest to use the convention where git commit message has the following format (if we have one commit per feature):
rfr-\<Issue Number\> \<Issue Title\>

we might have a few (but not more :) ) commits in scope of one feature-branch, but basically it should have the above format with replacing \<Issue Title\> with the description of extra work.

**Comment by qUser13** [comment]
A had a few questions:
@fin1989 - for 'com.squareup.okhttp:okhttp:2.2.0' and 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'. Do we need the first one, as for retrofit okhttp3 is added as dependency? For the second one - do we need it at all?

@Vovchyk - do we need just add it as dependency or build a simple structure with it and use it in the future? E.g. for retrofit - should we build a simple API framework and just use/expand it or it will be a separate task?

**Comment by Vovchyk** [comment]
> @fin1989 - for 'com.squareup.okhttp:okhttp:2.2.0' and 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'. Do we need the first one, as for retrofit okhttp3 is added as dependency? For the second one - do we need it at all?

@qUser13, good point - the only reason we would need to explicitly add a dependency on okhttp is when we need a newest version of it. But in this case the dependency on okhttp could be omitted.

> @Vovchyk - do we need just add it as dependency or build a simple structure with it and use it in the future? E.g. for retrofit - should we build a simple API framework and just use/expand it or it will be a separate task?

@qUser13, as we don't know how and what api we will use, I guess it's enough for now.

The main goal for now is to work out the process and collaboration between us using such tools and technics as git and PRs.

**Pull request closed without merging**
