### PR TITLE
rfr-13 Add Firebase Core and Auth Integration

### PR DESCRIPTION
**Pull request by fin1989**

### CODE REVIEW

**Comment by Vovchyk** [comment]
@fin1989, almost perfect :) it's left to rename commit "rfr-13_Add_Firebase" onto "rfr-13 Add Firebase Core and Auth Integration"

**Comment by fin1989** [comment]
@Vovchyk Done

**Comment by Vovchyk** [comment]
+1

**Comment by Vovchyk** [comment]
Seems your branch has some conflicts with master. git rebase on master may help you here. If you have any questions just let me know.

**Pull request merged**
